### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by jalil49** [DeathWeasel1337/BepInEx.Analyzers#1]
CSC : warning AD0001: Analyzer 'BepInEx.Analyzers.HarmonyPropertyPatchAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
Tried installing on Visual Studio 2019 and the analyzer throws this

**Comment by ghorsington** [comment]
Should be fixed in 1.0.6
